sudo: true
language: go
go:
  - 1.4.2
os:
  - linux
before_install:
  - sudo apt-get install libpcap-dev
  - go get github.com/mattn/gom
  - go get github.com/mitchellh/gox
  - gox -build-toolchain
script:
  - "./travis.sh"
  - gox
cache:
  directories:
    - "$HOME/gopath"