sudo: true
language: go
go:
  - 1.4.2
os:
  - linux
before_install:
  - sudo apt-get install libpcap-dev
  - go get github.com/mattn/gom
script:
  - $HOME/gopath/bin/gom install
  - $HOME/gopath/bin/gom test
